services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: python_app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1