services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile 
    container_name: python_app
    volumes:
      - .:/app
    ports:
      - "80:80"
    environment:
      - PYTHONUNBUFFERED=1